alias ff='fastfetch'
alias ls='eza -lh --group-directories-first --icons=auto'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias i='yay -S'
alias r='yay -Rns'
alias s='yay -Ss'
alias info='yay -Si'
alias cat='bat'
alias op='opencode'
alias vi='nvim'
alias ai='aichat'
